version: '3.8'

services:
  api:
    build:
      context: .
      cache_from:
        - eu.gcr.io/slam-lang/slam-runner-api:latest
    image: eu.gcr.io/slam-lang/slam-runner-api
    environment:
      PORT: 4000
      NEWRELIC_LICENSE_KEY: ${NEWRELIC_LICENSE_KEY}
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src
