version: '3'

services:
  api:
    build: .
    image: eu.gcr.io/slam-lang/slam-runner-api
    environment:
      PORT: 4000
      NEWRELIC_LICENSE_KEY: ${NEWRELIC_LICENSE_KEY}
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src
